### ISSUE TITLE
Keyboards crashing

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-dev-keyboard#3]
At least the following keyboards are crashing when activated:

- Meänkieli/fit
- Runic Nynorsk/nn-Runr
- Livvi/olo
- South Sámi

iOS version: 17.5.1
Model: XS Max

@zoomix this is high priority.

**Comment by snomos** [comment]
Here's a [video](https://failiem.lv/f/6kwcvukn2m) showing a number of issues including crashes, with oral comments.

**Comment by SteffenErn** [comment]
WIP: 
Livvi/olo cashes on iOS due to an issue with the KeyboardDefinitions.json file
```BaseKeyboard/KeyboardViewController.swift:250: Fatal error: Error getting keyboard definitions from json file: keyNotFound(Keys(stringValue: "normal", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 9", intValue: 9), Keys(stringValue: "ipad-9in", intValue: nil)], debugDescription: "No value associated with key Keys(stringValue: \"normal\", intValue: nil) (\"normal\").", underlyingError: nil))```
However during build process this file is correct. Investigating further...

**Comment by SteffenErn** [comment]
This happens because [Livonian](https://github.com/giellalt/keyboard-liv) does not have keyboard definitions for iPad. Either those definitions get added, the keyboard removed from the app or the app changed so it doesn't crash on missing ipad definitions.
@snomos What should we do?

**Comment by SteffenErn** [comment]
[This](https://github.com/divvun/giellakbd-ios/commit/ca19a783710ea9a7f949f229562d8f631a04e9dc) commit fixes the crashing keyboards. New version of the dev app is submitted to app store and should be available soon

**Comment by snomos** [comment]
Looks almost good:
- Livonian keyboard is now available and working on iPhone
- no crashes detected after a short period of testing

There are still non-crashing issues on the iPad, see #4.
